Check for devkit-packages after checking for overrides

diff --git a/dk b/dk
--- a/dk
+++ b/dk
@@ -16,77 +16,6 @@ verbose() {
     echo -e "\e[1m\e[30m$1\e[0m"
 }
 
-# Print help for dk itself
-# show-dk-help() {
-#     echo ""
-#     echo "devkit: Devkit command runner"
-#     echo ""
-#     echo "usage: dk <command> [<args>]"
-#     echo "usage: dk ls"
-#     echo ""
-#     exit 0
-# }
-
-# get-packages-path() {
-#     local devkit_packages_dir="./devkit-packages"
-#     if [ ! "$DEVKIT_SRC_DIR" = "" ]; then
-#         devkit_packages_dir="$DEVKIT_SRC_DIR"
-#     fi
-#     echo "$devkit_packages_dir"
-# }
-
-# enumerate-paths() {
-#     local command="$(to-snake-case "$1").py"
-
-#     echo "./devkit/commands/${command}"
-#     echo "$(get-packages-path)/devkit/commands/${command}"
-# }
-
-# bullet() {
-#     while read line; do
-#         echo "- $line"
-#     done
-# }
-
-# to-snake-case() {
-#     echo "${1//-/_}"
-# }
-
-# list-dir() {
-#     local dir="$1"
-#     if [ -d "$dir" ]; then
-#         (
-#             cd "$dir"
-#             find . -maxdepth 1 -name "*.py" -type f -print | \
-#                 sed 's|^./||' | \
-#                 grep -v "^_" | \
-#                 grep -v "^default$" |
-#                 sed 's/.py$//' | \
-#                 sed 's/_/-/' | \
-#                 bullet
-#         )
-#     else
-#         echo "(none)"
-#     fi
-# }
-
-# # Prints a list of all available commands
-# list() {
-#     echo
-#     echo "Project defined commands in ./devkit/commands:"
-#     echo
-
-#     list-dir "./devkit/commands"
-
-#     local devkit_packages_dir="$(get-packages-path)/devkit/commands"
-
-#     echo
-#     echo "Devkit commands in $devkit_packages_dir:"
-#     echo
-
-#     list-dir "$devkit_packages_dir"
-# }
-
 devkit-install-git-clone-internal() {
     local repo="$1"
     local temp_dir="$2"
@@ -164,7 +93,7 @@ devkit-install() {
             echo "Couldn't pull the latest devkit from a git repo"
             exit 1
         else
-            echo 
+            echo
             echo " - Devkit cloned successfully. Running installer..."
             echo
         fi
@@ -197,11 +126,6 @@ main() {
         error "Python version not supported: $python_version"
     fi
 
-    # if [ "$command" = "" ] || [ "$command" = "help" ] || [ "$command" = "--help" ] || [ "$command" = "-h" ]; then
-    #     show-dk-help
-    #     exit 0
-    # fi
-
     if [ "$command" = "--version" ] || [ "$command" = "-v" ]; then
         echo "dk: version $DK_VERSION, $python_version"
         exit 0
@@ -212,40 +136,6 @@ main() {
         exit 0
     fi
 
-    if [ ! -d ./devkit-packages ]; then
-        error "$error_banner Expected to find devkit installed at ./devkit-packages, but it was missing. Did you install devkit?"
-        exit 1
-    fi
-
-    # if [ "$command" = "ls" ]; then
-    #     echo "Available dk commands for this project:"
-
-    #     list
-
-    #     echo ""
-    #     exit 0
-    # fi
-
-#     local all_paths="$(enumerate-paths "$command")"
-#     local found_path
-
-#     while read -r script_path; do
-#         if [ -f "$script_path" ]; then
-#             found_path="$script_path"
-#             break
-#         fi
-#     done << EOF
-# $all_paths
-# EOF
-
-    # if [ "$found_path" = "" ]; then
-    #     error "${error_banner} No script was found at paths:"
-    #     echo "$all_paths" | while read script_path; do
-    #         error " - $script_path"
-    #     done
-    #     exit 1
-    # fi
-
     # Setup PYTHONPATH to read from devkit directories
     local current_dir="$(pwd)"
 
@@ -253,6 +143,11 @@ main() {
     local dev_dir="${current_dir}/devkit-packages"
     if [ ! "$DEVKIT_SRC_DIR" = "" ]; then
         dev_dir="$DEVKIT_SRC_DIR"
+    fi
+
+    if [ ! -d "$dev_dir" ]; then
+        error "$error_banner Expected to find devkit installed at ./devkit-packages, but it was missing. Did you install devkit?"
+        exit 1
     fi
 
     export PYTHONPATH="${current_dir}/devkit:${dev_dir}:${PYTHONPATH}"
