Better support for using a local dev dir

diff --git a/dk b/dk
--- a/dk
+++ b/dk
@@ -5,7 +5,7 @@ set -e
 export DK_VERSION="1.2.4"
 
 error() {
-    echo -e "\e[1m\e[31m$1\e[0m"
+    echo -e "\e[1m\e[31m$1\e[0m" >&2
 }
 
 bold() {
@@ -27,23 +27,19 @@ show-dk-help() {
     exit 0
 }
 
-# Converts the specified command to an executable script path
-get-script-path() {
-    local command="$1"
-
-    local script_path="./devkit/commands/${command}.py"
-
-    if [ -f "$script_path" ]; then
-        echo "$script_path"
-        return
+get-packages-path() {
+    local devkit_packages_dir="./devkit-packages"
+    if [ ! "$DEVKIT_SRC_DIR" = "" ]; then
+        devkit_packages_dir="$DEVKIT_SRC_DIR"
     fi
+    echo "$devkit_packages_dir"
+}
 
-    script_path="./devkit-packages/devkit/commands/${command}.py"
+enumerate-paths() {
+    local command="$(to-snake-case "$1").py"
 
-    if [ -f "$script_path" ]; then
-        echo "$script_path"
-        return
-    fi
+    echo "./devkit/commands/${command}"
+    echo "$(get-packages-path)/devkit/commands/${command}"
 }
 
 bullet() {
@@ -52,17 +48,26 @@ bullet() {
     done
 }
 
+to-snake-case() {
+    echo "${1//-/_}"
+}
+
 list-dir() {
     local dir="$1"
-    (
-        cd "$dir"
-        find . -maxdepth 1 -name "*.py" -type f -print | \
-            sed 's|^./||' | \
-            grep -v "^_" | \
-            grep -v "^default$" |
-            sed 's/.py$//' | \
-            bullet
-    )
+    if [ -d "$dir" ]; then
+        (
+            cd "$dir"
+            find . -maxdepth 1 -name "*.py" -type f -print | \
+                sed 's|^./||' | \
+                grep -v "^_" | \
+                grep -v "^default$" |
+                sed 's/.py$//' | \
+                sed 's/_/-/' | \
+                bullet
+        )
+    else
+        echo "(none)"
+    fi
 }
 
 # Prints a list of all available commands
@@ -73,11 +78,13 @@ list() {
 
     list-dir "./devkit/commands"
 
+    local devkit_packages_dir="$(get-packages-path)/devkit/commands"
+
     echo
-    echo "Devkit commands in ./devkit-packages/devkit/commands:"
+    echo "Devkit commands in $devkit_packages_dir:"
     echo
 
-    list-dir "./devkit-packages/commands"
+    list-dir "$devkit_packages_dir"
 }
 
 devkit-install-git-clone-internal() {
@@ -212,7 +219,6 @@ main() {
 
     if [ "$command" = "ls" ]; then
         echo "Available dk commands for this project:"
-        echo ""
 
         list
 
@@ -220,18 +226,36 @@ main() {
         exit 0
     fi
 
-    local script_path=$(get-script-path "$command")
+    local all_paths="$(enumerate-paths "$command")"
+    local found_path
 
-    if [ "$script_path" = "" ]; then
+    while read -r script_path; do
+        if [ -f "$script_path" ]; then
+            found_path="$script_path"
+            break
+        fi
+    done << EOF
+$all_paths
+EOF
 
-        error "${error_banner}No file was found for ./devkit/commands/${command}.py or ./devkit-packages/devkit/commands/${command}.py"
-        
+    if [ "$found_path" = "" ]; then
+        error "${error_banner} No script was found at paths:"
+        echo "$all_paths" | while read script_path; do
+            error " - $script_path"
+        done
         exit 1
     fi
 
     # Setup PYTHONPATH to read from devkit directories
     local current_dir="$(pwd)"
-    export PYTHONPATH="${current_dir}/devkit/devkit-overrides/:${current_dir}/devkit-packages:${PYTHONPATH}"
+
+    # If DEVKIT_SRC_DIR is specified, ignore the local directory and use the development version
+    local dev_dir="${current_dir}/devkit-packages"
+    if [ ! "$DEVKIT_SRC_DIR" = "" ]; then
+        dev_dir="$DEVKIT_SRC_DIR"
+    fi
+
+    export PYTHONPATH="${current_dir}/devkit/devkit-overrides:${dev_dir}:${PYTHONPATH}"
 
     #echo "PYTHONPATH: $PYTHONPATH"
 
